-- AlterEnum
ALTER TYPE "ShipmentStatus" ADD VALUE IF NOT EXISTS 'TIR_LOADED';
ALTER TYPE "ShipmentStatus" ADD VALUE IF NOT EXISTS 'TIR_DEPARTED';
ALTER TYPE "ShipmentStatus" ADD VALUE IF NOT EXISTS 'TIR_GEORGIA_BORDER';
ALTER TYPE "ShipmentStatus" ADD VALUE IF NOT EXISTS 'TIR_BAKU_CUSTOMS';
