ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "insuranceFirstName" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "insuranceLastName" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "insuranceDocSeries" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "insuranceTrustee" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "insuranceStatus" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "insuranceNotifiedAt" TIMESTAMP(3);
